name: Check quality
description: Check quality - lint and test

runs:
  using: "composite"
  steps:
    - name: Lint
      run: npm run lint
      shell: bash

    - name: Test
      run: npm run test
      shell: bash
