name: Initialize environment
description: Initialize environment for CI/CD process

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - name: Install dependencies
      run: npm ci
      shell: bash
